### ISSUE TITLE
Cannot stop bastion instance

### ISSUE THREAD

**Issue by circulon** [smoketurner/serverless-vpc-plugin#492]
As bastion instances are not used heavily it makes sense to be able to stop them to reduce costs.
ie after deployment of vpc and using bastion for setup purposes and initial checks, stop the instance in the ec2 console.

It was previously possible but I cannot remember which version of this plugin.

Currently the Bastion and NatInstance ec2 instances throw this error when trying to stop them 
"Failed to stop the instance i-xxxxxxxxx
You can't stop the Spot Instance 'i-xxxxxx' because it is associated with a one-time Spot Instance request. You can only stop Spot Instances associated with persistent Spot Instance requests"

Can the spot instance type be adjusted to allow this please?

**Comment by geoseong** [comment]
I wanted to do the same case and I think I found some temp solution.

Go to EC2 web console and editing the `Auto Scaling Groups` 's configuration make my bastion host instance shutting down automatically.

![image](https://user-images.githubusercontent.com/19166187/105487506-931ea700-5cf3-11eb-876d-9c717666ea7a.png)

![image](https://user-images.githubusercontent.com/19166187/105487143-f956fa00-5cf2-11eb-8161-a46b3031b1c9.png)

change value **0** in `Desired capacity`, `Minimum capacity` and `Maximum capacity` in **Group size** section and **Update** to save.

then Spot Requests and Bastion Instance's status will be closed and Terminated.

**Comment by danielstandby** [comment]
Instance can't be stopped because is part of a launch group. That's why you get that error when you try to stop it.

That said, I'm also interested in a way to auto stop idle bastion instance. For example you could check every 5 (or whatever) minutes if there are active SSH connections, if check is empty then stop the instance.

The problem is that it can't be done as long as the instance is part of a launch group. You would have to change the action to setting desired, minimum and maximum capacity to 0.
